name: dotnet-build-test-publish
run-name: .NET Build, Test & Publish
permissions:
  contents: read
  checks: write
  pull-requests: write
on:
  push:
  schedule:
    - cron: '0 4 * * SUN'
jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    env:
      CONFIGURATION: Release
      TARGET_FRAMEWORK: net10.0
    steps:
    - name: checkout
      uses: actions/checkout@v6

    - name: install dotnet
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: restore
      run: dotnet restore

    - name: build
      run: dotnet build --no-restore --configuration ${{ env.CONFIGURATION }}

    - name: install Playwright
      run: pwsh Wizdle.Web.Functional.Tests/bin/${{ env.CONFIGURATION }}/${{ env.TARGET_FRAMEWORK }}/playwright.ps1 install --with-deps chromium --only-shell

    - name: test - Wizdle.Unit.Tests
      run: dotnet test Wizdle.Unit.Tests/Wizdle.Unit.Tests.csproj --no-build --configuration ${{ env.CONFIGURATION }} --logger "trx;LogFileName=Wizdle.Unit.Tests.trx"

    - name: test - Wizdle.Integration.Tests
      run: dotnet test Wizdle.Integration.Tests/Wizdle.Integration.Tests.csproj --no-build --configuration ${{ env.CONFIGURATION }} --logger "trx;LogFileName=Wizdle.Integration.Tests.trx"

    - name: build Docker - Wizdle.Api
      run: make build-api

    - name: test - Wizdle.Api.Functional.Tests
      run: dotnet test Wizdle.Api.Functional.Tests/Wizdle.Api.Functional.Tests.csproj --no-build --configuration ${{ env.CONFIGURATION }} --logger "trx;LogFileName=Wizdle.Api.Functional.Tests.trx"

    - name: build Docker - Wizdle.Web
      run: make build-web

    - name: test - Wizdle.Web.Functional.Tests
      run: dotnet test Wizdle.Web.Functional.Tests/Wizdle.Web.Functional.Tests.csproj --no-build --configuration ${{ env.CONFIGURATION }} --logger "trx;LogFileName=Wizdle.Web.Functional.Tests.trx"

    - name: upload artifacts - Wizdle.Web.Functional.Tests
      uses: actions/upload-artifact@v4
      if: (!cancelled())
      with:
        name: Wizdle.Web.Functional.Tests
        retention-days: 30
        if-no-files-found: warn
        path: |
          Wizdle.Web.Functional.Tests/bin/**/reports/
          Wizdle.Web.Functional.Tests/bin/**/screenshots/
          Wizdle.Web.Functional.Tests/bin/**/playwright-traces/

    - name: publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: (!cancelled())
      with:
        files: '**/*.trx'

    - name: nuget push - NuGet
      if: success() && github.ref == 'refs/heads/master'
      run: dotnet nuget push **.nupkg --api-key ${{secrets.NUGET}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate

    - name: nuget push - GitHub
      if: success() && github.ref == 'refs/heads/master'
      run: dotnet nuget push **.nupkg --api-key ${{secrets.GITHUB}} --source "https://nuget.pkg.github.com/lyndychivs/index.json" --skip-duplicate
