name: dotnet-build-test-publish
run-name: .NET Build, Test & Publish
permissions:
  contents: read
on:
  push:
  schedule:
    - cron: '0 4 * * SUN'
jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v6

    - name: install dotnet
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: restore
      run: dotnet restore

    - name: build
      run: dotnet build --no-restore --configuration Release

    - name: install playwright
      run: |
        $script = Get-ChildItem -Path . -Recurse -Filter playwright.ps1 | Select-Object -First 1
        & $script.FullName install --with-deps
      shell: pwsh

    - name: test
      run: dotnet test --no-build --configuration Release

    - name: nuget push - NuGet
      if: github.ref == 'refs/heads/master'
      run: dotnet nuget push **.nupkg --api-key ${{secrets.NUGET}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate

    - name: nuget push - GitHub
      if: github.ref == 'refs/heads/master'
      run: dotnet nuget push **.nupkg --api-key ${{secrets.GITHUB}} --source "https://nuget.pkg.github.com/lyndychivs/index.json" --skip-duplicate